version: 2.1
commands:
  # Assumes a checkout is already available
  npm_install:
    description: Cached NPM Install
    steps:
      - run:
          name: Set Node Version File
          command: node --version > nodeversion
      - restore_cache:
          key: dependency-cache-node-{{ checksum "nodeversion" }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install --no-audit
      - save_cache:
          key: dependency-cache-node-{{ checksum "nodeversion" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  build:
    description: Build
    steps:
      - run:
          name: Build
          command: npm run build

jobs:
  build:
    docker:
      - image: brimsec/ci:0.0.1-zeek-mergecap
    steps:
      - checkout
      - npm_install
      - run:
          name: Format
          command: npm run format-check
      - build
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Flow
          command: npm run flow
      - run:
          name: Unit Tests
          command: npm test -- --maxWorkers=2 --ci
  integration_tests:
    docker:
      - image: brimsec/ci:0.0.1-zeek-mergecap
    steps:
      - checkout
      - npm_install
      - build
      - run:
          name: Get ZQD
          command: |
            git clone --single-branch https://github.com/brimsec/zq
            pushd zq
            git reset --hard da56b01d87a9745c90d09e960163ecba33eab55a
            make install
      - run:
          name: Integration Tests
          command: npm run itest
      - store_artifacts:
          path: /home/circleci/project/logs
      - store_artifacts:
          path: /home/circleci/.npm/_logs
workflows:
  version: 2
  main:
    jobs:
      - build
      - integration_tests:
          requires:
            - build
